services:
  db:
    image: postgres:11
    restart: always
    env_file:
      - .env
    volumes:
      - "./geodata/Universitas.csv:/geodata/Universitas.csv"
      - "./sql:/docker-entrypoint-initdb.d"
    ports:
      - 5400:5432